# Generated by Django 5.2.7 on 2025-10-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeltemplate',
            name='height_mm',
        ),
        migrations.RemoveField(
            model_name='labeltemplate',
            name='width_mm',
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='layout_height_mm',
            field=models.PositiveIntegerField(default=50, help_text='Высота области макета (под обрез) в миллиметрах', verbose_name='Высота области макета (мм)'),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='layout_width_mm',
            field=models.PositiveIntegerField(default=100, help_text='Ширина области макета (под обрез) в миллиметрах', verbose_name='Ширина области макета (мм)'),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='margin_bottom_mm',
            field=models.PositiveIntegerField(default=0, help_text='Отступ от нижнего края макета до области печати', verbose_name='Отступ снизу (мм)'),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='margin_left_mm',
            field=models.PositiveIntegerField(default=0, help_text='Отступ от левого края макета до области печати', verbose_name='Отступ слева (мм)'),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='margin_right_mm',
            field=models.PositiveIntegerField(default=0, help_text='Отступ от правого края макета до области печати', verbose_name='Отступ справа (мм)'),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='margin_top_mm',
            field=models.PositiveIntegerField(default=0, help_text='Отступ от верхнего края макета до области печати', verbose_name='Отступ сверху (мм)'),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='print_height_mm',
            field=models.PositiveIntegerField(default=50, help_text='Высота области печати в миллиметрах', verbose_name='Высота области печати (мм)'),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='print_width_mm',
            field=models.PositiveIntegerField(default=100, help_text='Ширина области печати в миллиметрах', verbose_name='Ширина области печати (мм)'),
        ),
    ]
