# Generated by Django 5.2.7 on 2025-10-16 13:21

import label_templates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_templates', '0002_remove_labeltemplate_height_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltemplate',
            name='template_file',
            field=models.FileField(blank=True, help_text='Файл шаблона этикетки (необязательно - можно создать шаблон без файла)', null=True, upload_to=label_templates.models.template_upload_path, verbose_name='Файл шаблона'),
        ),
    ]
