# Generated by Django 5.2.7 on 2025-10-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_templates', '0003_alter_labeltemplate_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('barcode', 'Штрих-код'), ('qr', 'QR-код'), ('datamatrix', 'DataMatrix (DS)'), ('image', 'Изображение')], default='text', help_text='Тип данных поля', max_length=20, verbose_name='Тип поля'),
        ),
    ]
