# Generated by Django 5.2.7 on 2025-10-25 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_sources", "0008_datacolumn_remove_csvdata_csv_column_and_more"),
        ("label_templates", "0004_alter_templatefield_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateusage",
            name="data_source",
            field=models.ForeignKey(
                help_text="CSV файл с данными для генерации",
                on_delete=django.db.models.deletion.CASCADE,
                to="data_sources.datauploadlog",
                verbose_name="Источник данных",
            ),
        ),
    ]
