# Generated by Django 5.2.7 on 2025-10-16 12:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Название загруженного CSV файла', max_length=255, verbose_name='Наименование файла')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время загрузки файла', verbose_name='Дата загрузки')),
                ('file_size', models.PositiveIntegerField(help_text='Размер загруженного файла в байтах', verbose_name='Размер файла (байт)')),
                ('rows_count', models.PositiveIntegerField(help_text='Общее количество строк в CSV файле', verbose_name='Количество строк')),
                ('columns_count', models.PositiveIntegerField(help_text='Количество столбцов в CSV файле', verbose_name='Количество столбцов')),
                ('status', models.CharField(choices=[('uploading', 'Загружается'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('error', 'Ошибка')], default='uploading', help_text='Текущий статус обработки файла', max_length=20, verbose_name='Статус обработки')),
                ('error_message', models.TextField(blank=True, help_text='Описание ошибки, если она возникла', null=True, verbose_name='Сообщение об ошибке')),
                ('author', models.ForeignKey(help_text='Пользователь, загрузивший файл', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор загрузки')),
            ],
            options={
                'verbose_name': 'Журнал загрузки CSV',
                'verbose_name_plural': 'Журнал загрузок CSV',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(help_text='Номер строки в CSV файле (начиная с 1)', verbose_name='Номер строки')),
                ('column_number', models.PositiveIntegerField(help_text='Номер столбца в CSV файле (начиная с 1)', verbose_name='Номер столбца')),
                ('column_name', models.CharField(blank=True, help_text='Название столбца (из первой строки CSV)', max_length=255, null=True, verbose_name='Название столбца')),
                ('cell_value', models.TextField(help_text='Содержимое ячейки CSV файла', verbose_name='Значение ячейки')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи в базе данных', verbose_name='Дата создания записи')),
                ('upload_log', models.ForeignKey(help_text='Ссылка на запись в журнале загрузки', on_delete=django.db.models.deletion.CASCADE, related_name='csv_data', to='data_sources.csvuploadlog', verbose_name='Журнал загрузки')),
            ],
            options={
                'verbose_name': 'Данные CSV',
                'verbose_name_plural': 'Данные CSV',
                'ordering': ['upload_log', 'row_number', 'column_number'],
                'indexes': [models.Index(fields=['upload_log', 'row_number'], name='data_source_upload__742926_idx'), models.Index(fields=['upload_log', 'column_number'], name='data_source_upload__8f0118_idx'), models.Index(fields=['column_name'], name='data_source_column__cd2f8f_idx')],
            },
        ),
    ]
