# Generated by Django 5.2.7 on 2025-10-16 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvuploadlog',
            name='has_headers',
            field=models.BooleanField(default=False, help_text='Отметьте, если первая строка содержит названия столбцов', verbose_name='Содержит заголовки столбцов'),
        ),
        migrations.CreateModel(
            name='CSVColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_number', models.PositiveIntegerField(help_text='Порядковый номер столбца в CSV файле (начиная с 1)', verbose_name='Номер столбца')),
                ('column_name', models.CharField(help_text='Название столбца из заголовка CSV файла', max_length=255, verbose_name='Название столбца')),
                ('original_name', models.CharField(blank=True, help_text='Оригинальное название столбца (если было изменено)', max_length=255, null=True, verbose_name='Оригинальное название')),
                ('data_type', models.CharField(blank=True, help_text='Определенный тип данных столбца (text, number, date, etc.)', max_length=50, null=True, verbose_name='Тип данных')),
                ('is_required', models.BooleanField(default=False, help_text='Является ли столбец обязательным для заполнения', verbose_name='Обязательный столбец')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание назначения столбца', null=True, verbose_name='Описание столбца')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи о столбце', verbose_name='Дата создания')),
                ('upload_log', models.ForeignKey(help_text='Ссылка на запись в журнале загрузки', on_delete=django.db.models.deletion.CASCADE, related_name='csv_columns', to='data_sources.csvuploadlog', verbose_name='Журнал загрузки')),
            ],
            options={
                'verbose_name': 'Столбец CSV',
                'verbose_name_plural': 'Столбцы CSV',
                'ordering': ['upload_log', 'column_number'],
                'indexes': [models.Index(fields=['upload_log', 'column_number'], name='data_source_upload__3e5b34_idx'), models.Index(fields=['column_name'], name='data_source_column__d3ae47_idx')],
                'unique_together': {('upload_log', 'column_number')},
            },
        ),
    ]
