# Generated by Django 5.2.7 on 2025-10-16 13:00

import data_sources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0002_csvuploadlog_has_headers_csvcolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvuploadlog',
            name='original_file',
            field=models.FileField(blank=True, help_text='Оригинальный CSV файл, загруженный пользователем', null=True, upload_to=data_sources.models.csv_upload_path, verbose_name='Исходный файл'),
        ),
    ]
