# Generated by Django 5.2.7 on 2025-10-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0003_csvuploadlog_original_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvuploadlog',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='Размер загруженного файла в байтах', verbose_name='Размер файла (байт)'),
        ),
    ]
