# Generated by Django 5.2.7 on 2025-10-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0004_alter_csvuploadlog_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvuploadlog',
            name='delimiter',
            field=models.CharField(choices=[(',', 'Запятая (,)'), (';', 'Точка с запятой (;)'), ('\t', 'Табуляция (\\t)'), ('|', 'Вертикальная черта (|)'), (' ', 'Пробел ( )'), (':', 'Двоеточие (:)')], default=',', help_text='Символ, используемый для разделения столбцов в CSV файле', max_length=1, verbose_name='Разделитель столбцов'),
        ),
    ]
