# Generated by Django 5.2.7 on 2025-10-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0005_csvuploadlog_delimiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvuploadlog',
            name='columns_count',
            field=models.PositiveIntegerField(blank=True, help_text='Количество столбцов в CSV файле', null=True, verbose_name='Количество столбцов'),
        ),
        migrations.AlterField(
            model_name='csvuploadlog',
            name='rows_count',
            field=models.PositiveIntegerField(blank=True, help_text='Общее количество строк в CSV файле', null=True, verbose_name='Количество строк'),
        ),
    ]
