# Generated by Django 5.2.7 on 2025-10-17 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0006_alter_csvuploadlog_columns_count_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='csvdata',
            name='data_source_column__cd2f8f_idx',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='column_name',
        ),
        migrations.AddField(
            model_name='csvdata',
            name='csv_column',
            field=models.ForeignKey(blank=True, help_text='Ссылка на описание столбца CSV файла', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_data', to='data_sources.csvcolumn', verbose_name='Столбец CSV'),
        ),
        migrations.AddIndex(
            model_name='csvdata',
            index=models.Index(fields=['csv_column'], name='data_source_csv_col_e2e919_idx'),
        ),
    ]
