# Generated by Django 5.2.7 on 2025-10-25 19:12

import data_sources.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_sources", "0007_remove_csvdata_data_source_column__cd2f8f_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "column_number",
                    models.PositiveIntegerField(
                        help_text="Порядковый номер столбца в файле (начиная с 1)",
                        verbose_name="Номер столбца",
                    ),
                ),
                (
                    "column_name",
                    models.CharField(
                        help_text="Название столбца из заголовка файла",
                        max_length=255,
                        verbose_name="Название столбца",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True,
                        help_text="Оригинальное название столбца (если было изменено)",
                        max_length=255,
                        null=True,
                        verbose_name="Оригинальное название",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        blank=True,
                        help_text="Определенный тип данных столбца (text, number, date, etc.)",
                        max_length=50,
                        null=True,
                        verbose_name="Тип данных",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Является ли столбец обязательным для заполнения",
                        verbose_name="Обязательный столбец",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительное описание назначения столбца",
                        null=True,
                        verbose_name="Описание столбца",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи о столбце",
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Столбец данных",
                "verbose_name_plural": "Столбцы данных",
                "ordering": ["upload_log", "column_number"],
            },
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="upload_log",
        ),
        migrations.RemoveField(
            model_name="csvuploadlog",
            name="author",
        ),
        migrations.CreateModel(
            name="DataUploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Название загруженного файла",
                        max_length=255,
                        verbose_name="Наименование файла",
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Дата и время загрузки файла",
                        verbose_name="Дата загрузки",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Размер загруженного файла в байтах",
                        verbose_name="Размер файла (байт)",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("csv", "CSV файл"), ("xlsx", "Excel файл (XLSX)")],
                        default="csv",
                        help_text="Тип загруженного файла",
                        max_length=10,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "rows_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Общее количество строк в файле",
                        null=True,
                        verbose_name="Количество строк",
                    ),
                ),
                (
                    "columns_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Количество столбцов в файле",
                        null=True,
                        verbose_name="Количество столбцов",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Загружается"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Завершено"),
                            ("error", "Ошибка"),
                        ],
                        default="uploading",
                        help_text="Текущий статус обработки файла",
                        max_length=20,
                        verbose_name="Статус обработки",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Описание ошибки, если она возникла",
                        null=True,
                        verbose_name="Сообщение об ошибке",
                    ),
                ),
                (
                    "has_headers",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если первая строка содержит названия столбцов",
                        verbose_name="Содержит заголовки столбцов",
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        blank=True,
                        help_text="Название листа Excel файла (если применимо)",
                        max_length=255,
                        null=True,
                        verbose_name="Название листа",
                    ),
                ),
                (
                    "delimiter",
                    models.CharField(
                        choices=[
                            (",", "Запятая (,)"),
                            (";", "Точка с запятой (;)"),
                            ("\t", "Табуляция (\\t)"),
                            ("|", "Вертикальная черта (|)"),
                            (" ", "Пробел ( )"),
                            (":", "Двоеточие (:)"),
                        ],
                        default=",",
                        help_text="Символ, используемый для разделения столбцов в CSV файле",
                        max_length=1,
                        verbose_name="Разделитель столбцов",
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        blank=True,
                        help_text="Оригинальный файл, загруженный пользователем",
                        null=True,
                        upload_to=data_sources.models.data_file_upload_path,
                        verbose_name="Исходный файл",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Пользователь, загрузивший файл",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор загрузки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал загрузки данных",
                "verbose_name_plural": "Журнал загрузок данных",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="DataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        help_text="Номер строки в файле (начиная с 1)",
                        verbose_name="Номер строки",
                    ),
                ),
                (
                    "column_number",
                    models.PositiveIntegerField(
                        help_text="Номер столбца в файле (начиная с 1)",
                        verbose_name="Номер столбца",
                    ),
                ),
                (
                    "cell_value",
                    models.TextField(
                        help_text="Содержимое ячейки файла",
                        verbose_name="Значение ячейки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи в базе данных",
                        verbose_name="Дата создания записи",
                    ),
                ),
                (
                    "data_column",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ссылка на описание столбца файла",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_records",
                        to="data_sources.datacolumn",
                        verbose_name="Столбец данных",
                    ),
                ),
                (
                    "upload_log",
                    models.ForeignKey(
                        help_text="Ссылка на запись в журнале загрузки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_records",
                        to="data_sources.datauploadlog",
                        verbose_name="Журнал загрузки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись данных",
                "verbose_name_plural": "Записи данных",
                "ordering": ["upload_log", "row_number", "column_number"],
            },
        ),
        migrations.AddField(
            model_name="datacolumn",
            name="upload_log",
            field=models.ForeignKey(
                help_text="Ссылка на запись в журнале загрузки",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_columns",
                to="data_sources.datauploadlog",
                verbose_name="Журнал загрузки",
            ),
        ),
        migrations.DeleteModel(
            name="CSVColumn",
        ),
        migrations.DeleteModel(
            name="CSVData",
        ),
    ]
