# Generated by Django 5.2.7 on 2025-10-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_sources", "0008_datacolumn_remove_csvdata_csv_column_and_more"),
        ("label_generator", "0002_alter_labelgeneration_data_source"),
        ("label_templates", "0005_alter_templateusage_data_source"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CSVUploadLog",
        ),
        migrations.AddIndex(
            model_name="datarecord",
            index=models.Index(
                fields=["upload_log", "row_number"],
                name="data_source_upload__ef58c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datarecord",
            index=models.Index(
                fields=["upload_log", "column_number"],
                name="data_source_upload__88d551_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datarecord",
            index=models.Index(
                fields=["data_column"], name="data_source_data_co_0c0c6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datacolumn",
            index=models.Index(
                fields=["upload_log", "column_number"],
                name="data_source_upload__6babde_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datacolumn",
            index=models.Index(
                fields=["column_name"], name="data_source_column__aa95f9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datacolumn",
            unique_together={("upload_log", "column_number")},
        ),
    ]
